name: label
on: pull_request
jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest
    if: github.repository == 'brace-rs/project-template'
    steps:
    - if: github.event_name == 'pull_request' && github.event.action == 'opened'
      uses: TimonVS/pr-labeler-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: csi-lk/package-labeler@v1.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        workspace: crates
        prefix: crates/
